/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carRental.view;

import com.sun.javafx.scene.control.skin.CustomColorDialog;
import com.sun.org.apache.xpath.internal.axes.OneStepIterator;
import lk.ijse.carRental.pnl.Bookingpnl;
import lk.ijse.carRental.pnl.Customerpnl;
import lk.ijse.carRental.pnl.Dashboradpnl;
import lk.ijse.carRental.pnl.Driverpnl;
import lk.ijse.carRental.pnl.Ownerpnl;
import lk.ijse.carRental.pnl.VehicleTypepnl;
import lk.ijse.carRental.pnl.Vehiclepnl;

/**
 *
 * @author Nethadun PC
 */
public class Dashborad extends javax.swing.JFrame {

    /**
     * Creates new form Dashborad
     */
    public Dashborad() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Dashboradpnl dash=new Dashboradpnl();
        dash.setVisible(true);
        formpnl.removeAll();
        dash.setSize(formpnl.getSize());
        formpnl.add(dash);
        formpnl.revalidate();
        formpnl.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formpnl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formpnl.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout formpnlLayout = new javax.swing.GroupLayout(formpnl);
        formpnl.setLayout(formpnlLayout);
        formpnlLayout.setHorizontalGroup(
            formpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1700, Short.MAX_VALUE)
        );
        formpnlLayout.setVerticalGroup(
            formpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(formpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 0, 1700, 1080));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Customer_50px.png")); // NOI18N
        jLabel2.setText("Customer Infromation");
        jLabel2.setAlignmentX(10.0F);
        jLabel2.setAlignmentY(10.0F);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 40));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Type_16px.png")); // NOI18N
        jLabel1.setText("Vehicle Type Infromation");
        jLabel1.setAlignmentX(10.0F);
        jLabel1.setAlignmentY(10.0F);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Carpool_16px.png")); // NOI18N
        jLabel3.setText("Vehicle Infromation");
        jLabel3.setAlignmentX(10.0F);
        jLabel3.setAlignmentY(10.0F);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Driver_16px.png")); // NOI18N
        jLabel4.setText("Driver infromation");
        jLabel4.setAlignmentX(10.0F);
        jLabel4.setAlignmentY(10.0F);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 40));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\User Account_16px.png")); // NOI18N
        jLabel7.setText("Owner Infromation");
        jLabel7.setAlignmentX(10.0F);
        jLabel7.setAlignmentY(10.0F);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 40));

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel8.setText("SNS");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel9.setText("rent a car");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Car Rental_48px.png")); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Menu_16px.png")); // NOI18N
        jLabel11.setText("Dashborad");
        jLabel11.setAlignmentX(10.0F);
        jLabel11.setAlignmentY(10.0F);
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 40));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Booking_16px.png")); // NOI18N
        jLabel12.setText("VehicleBooking");
        jLabel12.setAlignmentX(10.0F);
        jLabel12.setAlignmentY(10.0F);
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 220, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Logout Rounded Left_48px.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Driverpnl driver=new Driverpnl();
        formpnl.removeAll();
        driver.setSize(formpnl.getSize());
        formpnl.add(driver);
        formpnl.revalidate();
        formpnl.repaint();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Vehiclepnl vehi=new Vehiclepnl();
        formpnl.removeAll();
        vehi.setSize(formpnl.getSize());
        formpnl.add(vehi);
        formpnl.revalidate();
        formpnl.repaint();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        VehicleTypepnl type=new VehicleTypepnl();
        formpnl.removeAll();
        type.setSize(formpnl.getSize());
        formpnl.add(type);
        formpnl.revalidate();
        formpnl.repaint();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Ownerpnl owner=new Ownerpnl();
        formpnl.removeAll();
        owner.setSize(formpnl.getSize());
        formpnl.add(owner);
        formpnl.revalidate();
        formpnl.repaint();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Customerpnl cust=new Customerpnl();
        formpnl.removeAll();
        cust.setSize(formpnl.getSize());
        formpnl.add(cust);
        formpnl.revalidate();
        formpnl.repaint();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Bookingpnl book=new Bookingpnl();
        formpnl.removeAll();
        book.setSize(formpnl.getSize());
        formpnl.add(book);
        formpnl.revalidate();
        formpnl.repaint();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Dashboradpnl dash=new Dashboradpnl();
        dash.setVisible(true);
        formpnl.removeAll();
        dash.setSize(formpnl.getSize());
        formpnl.add(dash);
        formpnl.revalidate();
        formpnl.repaint();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashborad().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formpnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
