/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carRental.pnl;

import lk.ijse.carRental.controller.CustomerController;
import lk.ijse.carRental.dto.CustomerDTO;
import lk.ijse.carRental.generater.IDGenerater;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.carRental.model.Customer;

/**
 *
 * @author Nethadun PC
 */
public class Customerpnl extends javax.swing.JPanel {
    private  DefaultTableModel dtm;
    /**
     * Creates new form Customer
     */
    public Customerpnl() {
        initComponents();
        dtm=(DefaultTableModel) jTable1.getModel();
        getAllCustomer();
        CustomerID();
        clearAll();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        txtcustaddress = new javax.swing.JTextField();
        txtcustnic = new javax.swing.JTextField();
        txtmobilenum = new javax.swing.JTextField();
        txtcustid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtcustdrivindlic = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1669, 77));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CUSTOMER INFORMATION FROM");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Customer_48px.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1170, -1));

        jLabel2.setText("Customer NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, 20));

        jLabel3.setText("Customer ADDRESS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 20));

        jLabel4.setText("Customer NIC");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 20));

        jLabel5.setText("Customer MOBILE NUMBER");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 210, 20));

        jLabel6.setText("Customer ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, 20));

        txtcustname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtcustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustnameActionPerformed(evt);
            }
        });
        add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 190, -1));

        txtcustaddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtcustaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustaddressActionPerformed(evt);
            }
        });
        add(txtcustaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, -1));

        txtcustnic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtcustnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustnicActionPerformed(evt);
            }
        });
        add(txtcustnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 190, -1));

        txtmobilenum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txtmobilenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 190, -1));

        txtcustid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtcustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustidActionPerformed(evt);
            }
        });
        add(txtcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 190, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 255));
        jButton3.setText("REFERSH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 430, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUST ID", "CUST NAME", "CUST ADDRESS", "CUST NiC", "CUST DRIV LIC", "CUST MOBILE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 560, 450));

        jLabel7.setText("Customer DRIVING LICENCE");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 20));

        txtcustdrivindlic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtcustdrivindlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustdrivindlicActionPerformed(evt);
            }
        });
        add(txtcustdrivindlic, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtcustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustidActionPerformed
        try {
            String custId=txtcustid.getText();
            CustomerDTO searchCustomer=CustomerController.searchCustomer(custId);
            txtcustid.setText(searchCustomer.getCust_Id());
            txtcustname.setText(searchCustomer.getCust_Name());
            txtcustaddress.setText(searchCustomer.getCust_Address());
            txtcustnic.setText(searchCustomer.getCust_NIC());
            txtcustdrivindlic.setText(searchCustomer.getCust_Driv_Lic());
            txtmobilenum.setText(searchCustomer.getCust_Mobile_Num()+ "");
            txtcustname.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtcustidActionPerformed

    private void txtcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnameActionPerformed
        String cusName=txtcustname.getText();
        if(Pattern.compile("^[A-Z][a-z]{0,10}+[\\s][A-Z][a-z]*{0,10}+[\\s][A-Z][a-z]*{0,10}$").matcher(cusName).matches()){
            txtcustaddress.requestFocus();
        }else{
                  JOptionPane.showMessageDialog(this, "Format is invali");
                 }
        
    }//GEN-LAST:event_txtcustnameActionPerformed

    private void txtcustaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustaddressActionPerformed
        txtcustnic.requestFocus();
    }//GEN-LAST:event_txtcustaddressActionPerformed

    private void txtcustnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnicActionPerformed
        txtcustdrivindlic.requestFocus();
    }//GEN-LAST:event_txtcustnicActionPerformed

    private void txtcustdrivindlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustdrivindlicActionPerformed
        txtmobilenum.requestFocus();
    }//GEN-LAST:event_txtcustdrivindlicActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String custId=txtcustid.getText();
            String custName=txtcustname.getText();
            String custAddress=txtcustaddress.getText();
            String custNIC=txtcustnic.getText();
            String custDrILic=txtcustdrivindlic.getText();
            int custMobile=Integer.parseInt(txtmobilenum.getText());
            
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            Object rowData[]={custId,custName,custAddress,custNIC,custDrILic,custMobile};
            model.addRow(rowData);
            
            CustomerDTO cust=new CustomerDTO(custId, custName, custAddress, custNIC, custDrILic, custMobile);
            boolean b=CustomerController.addCustomer(cust);
            if(b){
                clearAll();
                getAllCustomer();
                JOptionPane.showMessageDialog(this, "ADD...");
            }else{
                JOptionPane.showMessageDialog(this, "FAILD...");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String cusId=txtcustid.getText();
            String cusName=txtcustname.getText();    
            String cusAddress=txtcustaddress.getText();
            String cusNic=txtcustnic.getText();
            String cusDrivingLision=txtcustdrivindlic.getText();
            int cusMobile =Integer.parseInt(txtmobilenum.getText());
            
            CustomerDTO cust=new CustomerDTO(cusId, cusName, cusAddress, cusNic, cusDrivingLision, cusMobile);
            boolean b=CustomerController.updateCustomer(cust);
            if(b){
                clearAll();
                getAllCustomer();
                JOptionPane.showMessageDialog(this, "UPDATE...");
            }else{
                JOptionPane.showMessageDialog(this, "FAILD...");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String custId=txtcustid.getText();
            
            boolean b=CustomerController.deleteCustomer(custId);
            if(b){
                clearAll();
                getAllCustomer();
                JOptionPane.showMessageDialog(this, "DELETE...");
            }else{
                JOptionPane.showMessageDialog(this, "FAILD...");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            getAllCustomer();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow=jTable1.getSelectedRow();
        String custId=dtm.getValueAt(selectedRow, 0).toString();
        String custName=dtm.getValueAt(selectedRow, 1).toString();
        String custAddress=dtm.getValueAt(selectedRow, 2).toString();
        String nic=dtm.getValueAt(selectedRow, 3).toString();
        String driverLic=dtm.getValueAt(selectedRow, 4).toString();
        String mobileNum=dtm.getValueAt(selectedRow, 5).toString();
        
        txtcustid.setText(custId);
        txtcustname.setText(custName);
        txtcustaddress.setText(custAddress);
        txtcustnic.setText(nic);
        txtcustdrivindlic.setText(driverLic);
        txtmobilenum.setText(mobileNum);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcustaddress;
    private javax.swing.JTextField txtcustdrivindlic;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtcustnic;
    private javax.swing.JTextField txtmobilenum;
    // End of variables declaration//GEN-END:variables

    private void getAllCustomer() {
        try {
            dtm.setRowCount(0);
            ArrayList<CustomerDTO> allCustomer=CustomerController.getAllCustomer();
            for (CustomerDTO customer : allCustomer) {
                Object[] rowData={customer.getCust_Id(),customer.getCust_Name(),customer.getCust_Address(),customer.getCust_NIC(),customer.getCust_Driv_Lic(),customer.getCust_Mobile_Num()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void CustomerID() {
        
        try {
            String custId;
            custId = IDGenerater.getNewID("customer", "cust_Id", "C");
            txtcustid.setText(custId);
        } catch (SQLException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void clearAll() {
         txtcustname.setText("");
         txtcustaddress.setText("");
         txtcustnic.setText("");
         txtcustdrivindlic.setText("");
         txtmobilenum.setText("");
         txtcustid.requestFocus();
    }
}
