/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carRental.pnl;

import lk.ijse.carRental.controller.DriverController;
import lk.ijse.carRental.controller.VehicleController;
import lk.ijse.carRental.dto.DriverDTO;
import lk.ijse.carRental.dto.VehicleDTO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nethadun PC
 */
public class Dashboradpnl extends javax.swing.JPanel {

    /**
     * Creates new form Dashborad
     */
    public Dashboradpnl() {
        initComponents();
        getLocalTime();
        getAllVehicle();
        getAllDriver();
        setDate();
        
        
        
    }

    private void getAllVehicle() {
        try {
            int veCount=0;
            ArrayList<VehicleDTO> allVehicle=VehicleController.getAllVehicle();
            for (VehicleDTO vehicle : allVehicle) {
                veCount++;
                lblVehicleCount.setText(" We have  "+veCount+"   Vehicles   ");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getAllDriver() {
        try {
            int driCount=0;
            ArrayList<DriverDTO> allDriver=DriverController.getAllDriver();
            for (DriverDTO driver : allDriver) {
                driCount++;
                lableDriver.setText(" We have  "+driCount+"   Drivers");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lableDriver = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblVehicleCount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labDate1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Menu_48px.png")); // NOI18N
        jLabel3.setText("DASHBORAD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 310, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1150, 77));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\images (1).jpg")); // NOI18N
        jLabel1.setText("Alto KK-4554");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 380, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\images.jpg")); // NOI18N
        jLabel2.setText("Prius CAD-3288");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 380, 170));

        lableDriver.setBackground(new java.awt.Color(51, 153, 255));
        lableDriver.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        lableDriver.setText("  WE HAVE 3 DRIVERS");
        lableDriver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        lableDriver.setOpaque(true);
        add(lableDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 300, 60));

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jLabel5.setText("              WE MANAGE ALL VEHICLES");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 580, 60));

        lblVehicleCount.setBackground(new java.awt.Color(51, 255, 102));
        lblVehicleCount.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        lblVehicleCount.setText("  WE HAVE 5 VEHICLE");
        lblVehicleCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        lblVehicleCount.setOpaque(true);
        add(lblVehicleCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 300, 60));

        jLabel7.setBackground(new java.awt.Color(51, 255, 204));
        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jLabel7.setText("  BEST COMPANY TO GET RENTED VEHICLE");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 580, 60));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTime.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        labTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(labTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, 40));

        jLabel4.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Time_48px.png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 40));

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 20));

        jLabel9.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Calendar_48px.png")); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 80, 40));

        jLabel8.setBackground(new java.awt.Color(255, 51, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        labDate1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        labDate1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(labDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 21, 140, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 280, 180));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labDate1;
    private javax.swing.JLabel labTime;
    private javax.swing.JLabel lableDriver;
    private javax.swing.JLabel lblVehicleCount;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        labDate1.setText(LocalDate.now().toString());
    }    

    private void getLocalTime() {
         new Thread(new Runnable() {
             @Override
             public void run() {
                 while(true){
                     Date curDate =new Date();
                     SimpleDateFormat dateFormat=new SimpleDateFormat("HH:mm:ss aa");
                     String currenTime=dateFormat.format(curDate);
                     
                     labTime.setText(currenTime);
                     try {
                         Thread.sleep(1000);
                     } catch (InterruptedException ex) {
                        
                     }
                 }
             }
         }).start();
    }
}
