/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carRental.pnl;

import lk.ijse.carRental.controller.DriverController;
import lk.ijse.carRental.dto.DriverDTO;
import lk.ijse.carRental.generater.IDGenerater;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nethadun PC
 */
public class Driverpnl extends javax.swing.JPanel {

    private DefaultTableModel dtm;

    /**
     * Creates new form Driverpnl
     */
    public Driverpnl() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();
        getAllDriver();
        setDriverId();
        clearAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dname = new javax.swing.JTextField();
        dage = new javax.swing.JTextField();
        did = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        daddress = new javax.swing.JTextField();
        dlisence = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 77));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Driver_48px.png")); // NOI18N
        jLabel4.setText("DRIVER INFROMATION FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        jLabel1.setText("Driver Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 20));

        jLabel2.setText("Driver Age");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, 20));

        jLabel3.setText("Driver ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 20));

        dname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        dname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnameActionPerformed(evt);
            }
        });
        add(dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, -1));

        dage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        dage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dageActionPerformed(evt);
            }
        });
        add(dage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 210, -1));

        did.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                didActionPerformed(evt);
            }
        });
        add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 255));
        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 410, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Driver ID", "Driver Name", "Driver Lisence", "AGE", "ADDRESS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 620, 400));

        jLabel5.setText("DriverAddress ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 140, 20));

        jLabel6.setText("Driver Lisence ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, 20));

        daddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        daddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daddressActionPerformed(evt);
            }
        });
        add(daddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 210, -1));

        dlisence.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        dlisence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlisenceActionPerformed(evt);
            }
        });
        add(dlisence, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnameActionPerformed
        String driverName = dname.getText();
        if (Pattern.compile("^[A-Z][a-z]{0,10}+[\\s][A-Z][a-z]*{0,10}+[\\s][A-Z][a-z]*{0,10}$").matcher(driverName).matches()) {
            dlisence.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Format is invali");
        }

    }//GEN-LAST:event_dnameActionPerformed

    private void dageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dageActionPerformed
        daddress.requestFocus();
    }//GEN-LAST:event_dageActionPerformed

    private void didActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_didActionPerformed
        try {
            String driverId = did.getText();
            DriverDTO searchDriver = DriverController.searchDriver(driverId);
            did.setText(searchDriver.getDriver_Id());
            dname.setText(searchDriver.getDriver_Name());
            dlisence.setText(searchDriver.getDriver_Licence());
            dage.setText(searchDriver.getDriver_Age() + "");
            daddress.setText(searchDriver.getDriver_Address());
            dname.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_didActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String driverId = did.getText();
            String driverName = dname.getText();
            String driverLisence = dlisence.getText();
            int driverAge = Integer.parseInt(dage.getText());
            String driverAddress = daddress.getText();

            DriverDTO update = new DriverDTO(driverId, driverName, driverLisence, driverAge, driverAddress);
            boolean u = DriverController.updateDriver(update);

            if (u) {
                clearAll();
                getAllDriver();
                JOptionPane.showMessageDialog(this, "UPDATE..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void daddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daddressActionPerformed
        btnAdd.requestFocus();
    }//GEN-LAST:event_daddressActionPerformed

    private void dlisenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlisenceActionPerformed
        dage.requestFocus();
    }//GEN-LAST:event_dlisenceActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String driverId = did.getText();
            String driverName = dname.getText();
            String driverLisence = dlisence.getText();
            int driverAge = Integer.parseInt(dage.getText());
            String driverAddress = daddress.getText();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] rowData = {driverId, driverName, driverLisence, driverAge, driverAddress};
            model.addRow(rowData);

            DriverDTO driver = new DriverDTO(driverId, driverName, driverLisence, driverAge, driverAddress);
            boolean a = DriverController.addDriver(driver);
            if (a) {
                getAllDriver();
                clearAll();
                JOptionPane.showMessageDialog(this, "ADD..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String driverId = did.getText();

            boolean d = DriverController.deleteDriver(driverId);

            if (d) {
                clearAll();
                getAllDriver();
                JOptionPane.showMessageDialog(this, "DELETE..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getAllDriver();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectRow = jTable1.getSelectedRow();
        String dId = dtm.getValueAt(selectRow, 0).toString();
        String dName = dtm.getValueAt(selectRow, 1).toString();
        String drivingLis = dtm.getValueAt(selectRow, 2).toString();
        String age = dtm.getValueAt(selectRow, 3).toString();
        String address = dtm.getValueAt(selectRow, 4).toString();

        did.setText(dId);
        dname.setText(dName);
        dlisence.setText(drivingLis);
        dage.setText(age);
        daddress.setText(address);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField daddress;
    private javax.swing.JTextField dage;
    private javax.swing.JTextField did;
    private javax.swing.JTextField dlisence;
    private javax.swing.JTextField dname;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void getAllDriver() {
        try {
            dtm.setRowCount(0);
            ArrayList<DriverDTO> allDriver = DriverController.getAllDriver();
            for (DriverDTO driver : allDriver) {
                Object[] rowData = {driver.getDriver_Id(), driver.getDriver_Name(), driver.getDriver_Licence(), driver.getDriver_Age(), driver.getDriver_Address()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDriverId() {
        try {
            String custId;
            custId = IDGenerater.getNewID("driver", "driver_Id", "D");
            did.setText(custId);
        } catch (SQLException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Driverpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAll() {
        dname.setText("");
        dlisence.setText("");
        dage.setText("");
        daddress.setText("");
        did.requestFocus();
    }
}
