/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carRental.pnl;

import lk.ijse.carRental.controller.OwnerController;
import lk.ijse.carRental.dto.OwnerDTO;
import lk.ijse.carRental.generater.IDGenerater;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nethadun PC
 */
public class Ownerpnl extends javax.swing.JPanel {

    private DefaultTableModel dtm;

    /**
     * Creates new form Ownerpnl
     */
    public Ownerpnl() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();
        getAllOwner();
        setOwnerID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ownername = new javax.swing.JTextField();
        owneradd = new javax.swing.JTextField();
        ownermob = new javax.swing.JTextField();
        ownerid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ownernic = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("OWNER INFORMATION FORM");

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Group_48px.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(379, 379, 379))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 77));

        jLabel2.setText("OWNER ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, 20));

        jLabel3.setText("OWNER ADDRESS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, 20));

        jLabel4.setText("OWNER MOBILE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 170, 20));

        jLabel5.setText("OWNER NAME");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 20));

        ownername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        ownername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownernameActionPerformed(evt);
            }
        });
        add(ownername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 190, -1));

        owneradd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        owneradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owneraddActionPerformed(evt);
            }
        });
        add(owneradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 190, -1));

        ownermob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        ownermob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownermobActionPerformed(evt);
            }
        });
        add(ownermob, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 190, -1));

        ownerid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        ownerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owneridActionPerformed(evt);
            }
        });
        add(ownerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, -1));

        jLabel6.setText("OWNER NIC");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 170, 20));

        ownernic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        ownernic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownernicActionPerformed(evt);
            }
        });
        add(ownernic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 190, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnAdd)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 471, 410, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OWNER ID", "OWNER NAME", "OWNER ADDRESS", "OWNER NIC", "OWNER MOB"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 120, 630, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void ownernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownernameActionPerformed
        String ownerName = ownername.getText();
        if (Pattern.compile("^[A-Z][a-z]{0,10}+[\\s][A-Z][a-z]*{0,10}+[\\s][A-Z][a-z]*{0,10}$").matcher(ownerName).matches()) {
            owneradd.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Format is invali");
        }

    }//GEN-LAST:event_ownernameActionPerformed

    private void owneraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owneraddActionPerformed
        ownernic.requestFocus();
    }//GEN-LAST:event_owneraddActionPerformed

    private void ownermobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownermobActionPerformed
        btnAdd.requestFocus();
    }//GEN-LAST:event_ownermobActionPerformed

    private void owneridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owneridActionPerformed
        try {
            String ownerId = ownerid.getText();
            OwnerDTO owner = OwnerController.searchOwner(ownerId);
            ownername.setText(owner.getOwner_Name());
            owneradd.setText(owner.getOwner_Address());
            ownernic.setText(owner.getOwner_NIC());
            ownermob.setText(owner.getOwner_Mob() + "");
            ownername.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_owneridActionPerformed

    private void ownernicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownernicActionPerformed
        ownermob.requestFocus();
    }//GEN-LAST:event_ownernicActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String ownerId = ownerid.getText();
            String ownerName = ownername.getText();
            String ownerAdd = owneradd.getText();
            String ownerNic = ownernic.getText();
            int ownerMob = Integer.parseInt(ownermob.getText());

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] rowData = {ownerId, ownerName, ownerAdd, ownerNic, ownerMob};
            model.addRow(rowData);

            OwnerDTO owner = new OwnerDTO(ownerId, ownerName, ownerAdd, ownerNic, ownerMob);
            boolean add = OwnerController.addOwner(owner);

            if (add) {
                JOptionPane.showMessageDialog(this, "ADD...");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String ownerId = ownerid.getText();
            String ownerName = ownername.getText();
            String ownerAdd = owneradd.getText();
            String ownerNic = ownernic.getText();
            int ownerMob = Integer.parseInt(ownermob.getText());

            OwnerDTO owner = new OwnerDTO(ownerId, ownerName, ownerAdd, ownerNic, ownerMob);
            boolean update = OwnerController.updateOwner(owner);

            if (update) {
                JOptionPane.showMessageDialog(this, "UPDATE..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String ownerId = ownerid.getText();

            boolean delete = OwnerController.deleteOwner(ownerId);

            if (delete) {
                JOptionPane.showMessageDialog(this, "DELETE..");
            } else {
                JOptionPane.showMessageDialog(this, "Faild..");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getAllOwner();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectRow = jTable1.getSelectedRow();
        String oId = dtm.getValueAt(selectRow, 0).toString();
        String oName = dtm.getValueAt(selectRow, 1).toString();
        String oAddress = dtm.getValueAt(selectRow, 2).toString();
        String oNic = dtm.getValueAt(selectRow, 3).toString();
        String oMobile = dtm.getValueAt(selectRow, 4).toString();

        ownerid.setText(oId);
        ownername.setText(oName);
        owneradd.setText(oAddress);
        ownernic.setText(oNic);
        ownermob.setText(oMobile);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField owneradd;
    private javax.swing.JTextField ownerid;
    private javax.swing.JTextField ownermob;
    private javax.swing.JTextField ownername;
    private javax.swing.JTextField ownernic;
    // End of variables declaration//GEN-END:variables

    private void getAllOwner() {
        try {
            dtm.setRowCount(0);
            ArrayList<OwnerDTO> allOwner = OwnerController.getAllOwner();
            for (OwnerDTO owner : allOwner) {
                Object[] rowData = {owner.getOwner_Id(), owner.getOwner_Name(), owner.getOwner_Address(), owner.getOwner_NIC(), owner.getOwner_Mob()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setOwnerID() {
        try {
            String custId;
            custId = IDGenerater.getNewID("owner", "owner_Id", "O");
            ownerid.setText(custId);
        } catch (SQLException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ownerpnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
