/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carRental.pnl;

import lk.ijse.carRental.controller.VehicleTypeController;
import lk.ijse.carRental.dto.VehicleTypeDTO;
import lk.ijse.carRental.generater.IDGenerater;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nethadun PC
 */
public class VehicleTypepnl extends javax.swing.JPanel {

    private DefaultTableModel dtm;

    /**
     * Creates new form vehicleTypepnl
     */
    public VehicleTypepnl() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();
        getAllVehicleType();
        setVehicleTypeId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        typeid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 77));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VEHICLE TYPE INFORMATION TABLE");

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Type_48px.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 77));

        jLabel2.setText("VEHICLE TYPE ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, 20));

        jLabel3.setText("VEHICLE CATEGORY ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 20));

        jLabel7.setText("VEHICLE TYPE ID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 20));

        type.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 170, -1));

        category.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 170, -1));

        typeid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        typeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeidActionPerformed(evt);
            }
        });
        add(typeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 170, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 410, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VEHICLE TYPE ID", "VEHICLE TYPE", "VEHICLE CATEGORY"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 127, 590, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String vehiTypeId = typeid.getText();
            String vehiType = type.getText();
            String vehiCate = category.getText();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] rowData = {vehiTypeId, vehiType, vehiCate};
            model.addRow(rowData);

            VehicleTypeDTO vehicleType = new VehicleTypeDTO(vehiTypeId, vehiType, vehiCate);
            boolean a = VehicleTypeController.addVehicleType(vehicleType);
            if (a) {
                JOptionPane.showMessageDialog(this, "ADD..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String vehiTypeId = typeid.getText();
            String vehiType = type.getText();
            String vehiCate = category.getText();

            VehicleTypeDTO vehicleType = new VehicleTypeDTO(vehiTypeId, vehiType, vehiCate);
            boolean u = VehicleTypeController.updateVehicleType(vehicleType);

            if (u) {
                JOptionPane.showMessageDialog(this, "UPDATE..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String vehiTypeId = typeid.getText();

            boolean d = VehicleTypeController.deletevehicleType(vehiTypeId);
            if (d) {
                JOptionPane.showMessageDialog(this, "DELETE..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void typeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeidActionPerformed
        try {
            String vehicleTypeId=typeid.getText();
            VehicleTypeDTO vehiType=VehicleTypeController.searchVehicle(vehicleTypeId);
            type.setText(vehiType.getVehicle_Type());
            category.setText(vehiType.getVehicle_Category());
            type.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_typeidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getAllVehicleType();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        category.requestFocus();
    }//GEN-LAST:event_typeActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        btnAdd.requestFocus();
    }//GEN-LAST:event_categoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField category;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField type;
    private javax.swing.JTextField typeid;
    // End of variables declaration//GEN-END:variables

    private void getAllVehicleType() {
        try {
            dtm.setRowCount(0);
            ArrayList<VehicleTypeDTO> allvehicleType = VehicleTypeController.getAllVehicleType();
            for (VehicleTypeDTO vehicleType : allvehicleType) {
                Object[] rowData = {vehicleType.getVehicle_Type_Id(), vehicleType.getVehicle_Type(), vehicleType.getVehicle_Category()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setVehicleTypeId() {
        try {
            String custId;
            custId = IDGenerater.getNewID("vehicle_Type", "vehicle_Type_Id", "T");
            typeid.setText(custId);
        } catch (SQLException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VehicleTypepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
