/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carRental.pnl;

import lk.ijse.carRental.controller.OwnerController;
import lk.ijse.carRental.controller.VehicleController;
import lk.ijse.carRental.controller.VehicleTypeController;
import lk.ijse.carRental.dto.OwnerDTO;
import lk.ijse.carRental.dto.VehicleDTO;
import lk.ijse.carRental.dto.VehicleTypeDTO;
import lk.ijse.carRental.generater.IDGenerater;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nethadun PC
 */
public class Vehiclepnl extends javax.swing.JPanel {

    private DefaultTableModel dtm;

    /**
     * Creates new form Vehiclepnl
     */
    public Vehiclepnl() {
        initComponents();
        loardAllOwner();
        loardAllVehicleTypes();
        dtm = (DefaultTableModel) jTable1.getModel();
        getAllVehicle();
        setVehicleID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        colour = new javax.swing.JTextField();
        rent = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        vehiId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cobowner = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comtype = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\jave nethadun\\carRentManagement\\src\\lk\\ijse\\carRental\\img\\Pickup Front View_48px.png")); // NOI18N
        jLabel1.setText("VEHICLE INFORMATION FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(385, 385, 385))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 77));

        jLabel6.setText("OWNER ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 20));

        jLabel7.setText("VEHICLE TYPE ID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 20));

        jLabel8.setText("RENT FOR DATE");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 20));

        jLabel9.setText("NO OF PASSANGERS");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 170, 20));

        jLabel10.setText("VEHICLE ID");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 20));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 102));
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 255, 255));
        jButton8.setText("REFRESH");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton8))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 410, -1));

        colour.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        colour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourActionPerformed(evt);
            }
        });
        add(colour, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, -1));

        rent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentActionPerformed(evt);
            }
        });
        add(rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 190, -1));

        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 190, -1));

        vehiId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        vehiId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiIdActionPerformed(evt);
            }
        });
        add(vehiId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 190, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VEHICLE ID", "VEHICLE TYPE ID", "COULOR", "RENT FOR DAY", "NO OF PASSENGERS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 600, 470));

        cobowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobownerActionPerformed(evt);
            }
        });
        add(cobowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 190, -1));

        jLabel11.setText("COLOUR");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 170, 20));

        comtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comtypeActionPerformed(evt);
            }
        });
        add(comtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void vehiIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiIdActionPerformed
        try {
            String vehicleId=vehiId.getText();
            VehicleDTO searchVehicle=VehicleController.searchVehicle(vehicleId);
            cobowner.setSelectedItem(searchVehicle.getOwner_Id());
            comtype.setSelectedItem(searchVehicle.getVehicle_Type_Id());
            colour.setText(searchVehicle.getColour());
            rent.setText(searchVehicle.getRent()+"");
            pass.setText(searchVehicle.getNo_Pass()+"");
            cobowner.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_vehiIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String vehicleId = vehiId.getText();
            String ownerID = cobowner.getSelectedItem().toString();
            String vehicleType = comtype.getSelectedItem().toString();
            String colur = colour.getText();
            double rentD = Double.parseDouble(this.rent.getText());
            int noOfPass = Integer.parseInt(pass.getText());

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] rowData = {vehicleId, vehicleType, colur, rentD, noOfPass};
            model.addRow(rowData);

            VehicleDTO vehicle = new VehicleDTO(vehicleId, ownerID, vehicleType, colur, rentD, noOfPass);
            boolean b = VehicleController.addVehicle(vehicle);

            if (b) {
                JOptionPane.showMessageDialog(this, "ADD..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String vehicleId = vehiId.getText();
            String ownerID = cobowner.getSelectedItem().toString();
            String vehicleType = comtype.getSelectedItem().toString();
            String colur = colour.getText();
            double rentD = Double.parseDouble(this.rent.getText());
            int noOfPass = Integer.parseInt(pass.getText());

            VehicleDTO vehicle = new VehicleDTO(vehicleId, ownerID, vehicleType, colur, rentD, noOfPass);
            boolean b = VehicleController.updateVehicle(vehicle);
            if (b) {
                JOptionPane.showMessageDialog(this, "UPDATE..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String vehicleId = vehiId.getText();

            boolean d = VehicleController.deleteVehicle(vehicleId);
            if (d) {
                JOptionPane.showMessageDialog(this, "DELETE..");
            } else {
                JOptionPane.showMessageDialog(this, "FAILD..");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cobownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobownerActionPerformed
        comtype.requestFocus();
    }//GEN-LAST:event_cobownerActionPerformed

    private void comtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comtypeActionPerformed
        colour.requestFocus();
    }//GEN-LAST:event_comtypeActionPerformed

    private void colourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourActionPerformed
        rent.requestFocus();
    }//GEN-LAST:event_colourActionPerformed

    private void rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentActionPerformed
        pass.requestFocus();
    }//GEN-LAST:event_rentActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        btnAdd.requestFocus();
    }//GEN-LAST:event_passActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cobowner;
    private javax.swing.JTextField colour;
    private javax.swing.JComboBox<String> comtype;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField rent;
    private javax.swing.JTextField vehiId;
    // End of variables declaration//GEN-END:variables

    private void loardAllOwner() {
        try {
            cobowner.removeAll();
            ArrayList<OwnerDTO> allOwner = OwnerController.getAllOwner();
            for (OwnerDTO ownerDTO : allOwner) {
                cobowner.addItem(ownerDTO.getOwner_Id());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getAllVehicle() {
        try {
            dtm.setRowCount(0);
            ArrayList<VehicleDTO> allVehicle = VehicleController.getAllVehicle();
            for (VehicleDTO vehicle : allVehicle) {
                Object[] rowData = {vehicle.getVehicle_Id(), vehicle.getVehicle_Type_Id(), vehicle.getColour(), vehicle.getRent(), vehicle.getNo_Pass()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loardAllVehicleTypes() {
        try {
            comtype.removeAll();
            ArrayList<VehicleTypeDTO> allvehicleType = VehicleTypeController.getAllVehicleType();
            for (VehicleTypeDTO vehicleTypeDTO : allvehicleType) {
                comtype.addItem(vehicleTypeDTO.getVehicle_Type_Id());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setVehicleID() {
        try {
            String custId;
            custId = IDGenerater.getNewID("vehicle", "vehicle_Id", "V");
            vehiId.setText(custId);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiclepnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
